# Use the official MySQL 8.0 image with Debian base
FROM mysql:8.0

# Set environment variables for the MySQL database
ENV MYSQL_ROOT_PASSWORD=!@bugdeaL3r
ENV MYSQL_DATABASE=db_crud

#add permissions to mysqld directory and sub folders
RUN chown -R mysql:mysql /var/run/mysqld && \
    chmod -R 777 /var/run/mysqld

# Switch to the MySQL user
USER mysql

# Expose MySQL port
EXPOSE 3306

# Start MySQL server
CMD ["mysqld"]
